argv 	= require('optimist')
	.usage('A helper script to analyse the data acquired with Fujifilm BAS-5000 plate reader.\nUsage: $0 --mode <mode> --file <datafile> --output <output-file>.')
	.alias('mode', 'm')
	.describe('mode', 'Mode for the helper script to process the data. (kinetics)')
	.default('mode', 'kinetics')
	.demand('mode')
	.alias('file', 'f')
	.describe('file', 'Data file generated by the plate reader.')
	.demand('file')
	.alias('filetype', 't')
	.describe('filetype', "Type of the input file.")
	.default('filetype', 'csv')
	.demand('filetype')
	.alias('output', 'o')
	.describe('output', 'output file for the result. CSV format.')
	.argv

csv 	= require 'csv'
fs 		= require 'fs'
path 	= require 'path'

class PlateReaderHelper
	constructor: () ->
		@support_file_types 	= ['csv'] #['csv', 'raw', 'excel']
		@support_mode			= ['kinetics']
		@datafile				= null
		@filetype 				= 'csv'
		@output 				= null
		@ready					= false
		@error_msg				= []
		@mode 					= 'kinetics'

	raise_error: (msg) ->
		@error_msg.push msg

	error_exit: ->
		for errmsg in @error_msg
			console.error errmsg
		process.exit 1

	has_error: ->
		return if @error_msg.length then true else false

	error: (msg) ->
		@raise_error msg
		@error_exit()

	set_datafile: (data_file) ->
		fn = path.resolve data_file
		exists = fs.existsSync fn
		@datafile = if exists then fn else null
		@raise_error "File #{data_file} does not exist." unless exists

	set_outputfile: (output_file) ->
		fn = path.resolve output_file
		exists = fs.existsSync fn
		@output = if exists then null else fn
		@error "Output File #{output_file} has already existed." if exists

	set_filetype: (filetype) ->
		filetype = filetype.toLowerCase()
		@filetype = if filetype in @support_file_types then filetype else null
		@raise_error "Unsupport file type \"#{filetype}\"." if @filetype is null

	set_mode: (mode) ->
		mode = mode.toLowerCase()
		@mode = if mode in @support_mode then mode else null
		@raise_error "Unsupport operating mode \"#{mode}\"." if @mode is null

	_readfile: (cb, self = @) ->
		error_exit() if self.has_error()
		switch self.filetype
			when 'csv', 'raw'
				fh = fs.createReadStream self.datafile
				self.ready = true
				cb(fh)
			else
				self.raise_error "Unsupport file type \"#{@filetype}\"."
				cb(null)

	_loadfile: (cb, self = @) ->
		func_loadfile = (fh) ->
			self.error_exit() unless self.ready
			switch self.filetype
				when 'csv'
					csv()
						.from.stream(fh)
						.to.array((data, count) ->
							cb data
						)
						.on('error', (err) ->
							self.error err
						)
				else
					@error "Unsupport file type \"#{@filetype}\"."

		self._readfile func_loadfile, self

	_parsefile: (cb, self = @) ->
		func_parsefile = (data_array) ->
			results = []
			
			switch self.mode
				when 'kinetics'
					
				else
					self.error "Unsupport mode!"

			cb data_array

		self._loadfile func_parsefile, self

	_formatoutput: (cb, self = @) ->
		func_formatoutput = (data) ->
			# do output part
			if self.output is null
				# output to screen
				console.log data
				cb data
			else
				# output to csv file
				data_array = []
				for row in data
					data_array.push row.join(",")

				fs.writeFile self.output, data_array.join("\n"), (err) ->
					if err
						self.error err
					else
						cb data

		self._parsefile func_formatoutput, self

	process: ->
		done = ->
			console.log "DONE!"

		@_formatoutput done, @	

main = ->
	prh = new PlateReaderHelper
	prh.set_datafile argv.file
	prh.set_filetype argv.filetype
	prh.set_outputfile argv.output if argv.output
	prh.set_mode argv.mode
	prh.process()


main()
